distance_m: 5
input_image_height: 640
input_image_width: 640
broker: "192.168.10.159"
port: 1883
client_id: 1
model_dtype: "float32"
mqtt_topic_name: "human-detected"
image_topic_name: '/oak/rgb/image_raw'
stereo_topic_name: '/oak/stereo/image_raw'